# Generated by Django 3.2 on 2023-11-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20231116_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.DateTimeField(verbose_name='Год выпуска'),
        ),
    ]
