# Generated by Django 3.2.20 on 2023-12-10 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Оценка меньше допустимой'), django.core.validators.MaxValueValidator(10, message='Оценка больше допустимой')], verbose_name='Оценка'),
        ),
    ]
